### PR TITLE
Stringtyps added and old improved & RAW added

### PR DESCRIPTION
**Pull request by PLCHome**
For 8-bit types, this becomes clear which byte is taken from the 16-bit value
Raw data as a hex string
Fix issue stringle was always converted to number for slave
Enable formula for strings and hex strings

### CODE REVIEW

**Comment by PLCHome** [comment]
Raw data as a hex string
Fix issue stringle was always converted to number for slave
Enable formula for strings and hex strings

Neuer Datentyp für Raw-Output möglich? https://github.com/ioBroker/ioBroker.modbus/issues/315


Ich habe eine Wallbox, die in jedes Wort ein Zeichen des Strings schreibt. Deswegen benötige ich einen 16bit String be.

Des weiteren schreibt die Wallbox in 5 Wörter Jahr, Monat, Tag, Stunde, Minute, Sekunde. Dieses kann man mit dem RAW String nun auslesen und mit einer Formel in einen Uhrzeitstring umwandeln und in dem Feld ablegen.

**Comment by Apollon77** [comment]
Thank you!

Please use 
**WORK IN PROGRESS** in readme for the changelog entry. the rerlease script fills this then automatically on release

**Comment by PLCHome** [comment]
> Thank you!
> 
> Please use **WORK IN PROGRESS** in readme for the changelog entry. the rerlease script fills this then automatically on release

is it ok like this?

**Comment by PLCHome** [comment]
Now it should be fine. Unfortunately, I found another error in the readme.md that I only saw on the 10th reading. 

Sorry about that

**Comment by PLCHome** [comment]
deleted after 2 months

**Comment by Apollon77** [comment]
Come on ... a poke and reminder would have been great instead of deleting it ...

**Comment by PLCHome** [comment]
@Apollon77 how does it look. Do we want to merge the changes?

**Comment by Apollon77** [comment]
yes will do on the weekend ... promised!

**Comment by Apollon77** [comment]
Ok ... release comes in some mins. Would be cool if you could verify when you have some mins, I also updated some depencies  ... thank you!

**Comment by Apollon77** [comment]
(released to npm ...)
And mega sorry that it took that long

**Pull request merged**
